### ISSUE TITLE
Discrepancy in pills

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-v3-tableau-cumulative-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6534/assignments/245182?module_item_id=577929

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

1. Part C seems to show a discrepancy between the instructions' screen shots and the actual sample data source used in Tableau. Specifically, there's no "Reginal Manager" pill in the "People" sheet. That seems to have been replaced by a "People" pill. Also, the names themselves are different (with one exception of "Chuck Magee" -- good for him). 

2. Then, in Part D, item #4, it instructs the student to add the "Sales" pill to the Marks card and select the "size" attribute, but I'm pretty sure it's meant to have the student select the "label" attribute. 

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
For better or worse, Tableau keeps updating this file, so the results are not static. I'll update this, but I'll also include statements regarding the file change possibilities. (And likewise, good for ole' Chuck Magee.)

**Comment by danielburdeno** [comment]
Updated with new images and instructions to match. Added in filtering across worksheets
