### ISSUE TITLE
Images shown to us and instructions provided does not yield the same result! confusing to follow and annoying for user

### ISSUE THREAD

**Issue by alecs1523** [learn-co-curriculum/dsc-v3-tableau-cumulative-lab#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. Thank you bringing this to our attention. Since this is the same issue as https://github.com/learn-co-curriculum/dsc-v3-tableau-cumulative-lab/issues/1, I'll close this issue. When I resolve this shared issue, I'll close it there.
