### ISSUE TITLE
Tableau Dashboards Cumulative Lab Lesson Issue

### ISSUE THREAD

**Issue by ckucewicz** [learn-co-curriculum/dsc-v3-tableau-cumulative-lab#3]
## Link to Canvas
<[!-- Add a link to the assignment in Canvas below this line --](https://learning.flatironschool.com/courses/7073/assignments/254936?module_item_id=602338)>

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [X ] Other (explain below)

### Source

```

```

### Concern

This lesson contains typos, and the formatting makes it difficult to follow the directions. It feels as though this lesson was not proof read.

## What OS Are You Using?

- [ X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
I'm cleaning this lesson up as I work on https://github.com/learn-co-curriculum/dsc-v3-tableau-cumulative-lab/issues/1.  So I'll close this, further updates will be with that issue. Thank you again.
